// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEKSg01gWA8Z4Kv0NPCUfH_DCu4D1jO6Q',
    appId: '1:611009879331:web:4c4382fe7d606e29328096',
    messagingSenderId: '611009879331',
    projectId: 'student-talent-profiling-eaede',
    authDomain: 'student-talent-profiling-eaede.firebaseapp.com',
    storageBucket: 'student-talent-profiling-eaede.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQQ73XZsQTxwL_QpiQbOImyPdXRNn5M3E',
    appId: '1:611009879331:android:cee3432f4da5c541328096',
    messagingSenderId: '611009879331',
    projectId: 'student-talent-profiling-eaede',
    storageBucket: 'student-talent-profiling-eaede.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4vpZ7EkQyRtq9VE7WlIzi9KZekRwuNTc',
    appId: '1:611009879331:ios:2b51a412c0f2dd68328096',
    messagingSenderId: '611009879331',
    projectId: 'student-talent-profiling-eaede',
    storageBucket: 'student-talent-profiling-eaede.firebasestorage.app',
    iosBundleId: 'com.example.studentTalentProfilingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4vpZ7EkQyRtq9VE7WlIzi9KZekRwuNTc',
    appId: '1:611009879331:ios:2b51a412c0f2dd68328096',
    messagingSenderId: '611009879331',
    projectId: 'student-talent-profiling-eaede',
    storageBucket: 'student-talent-profiling-eaede.firebasestorage.app',
    iosBundleId: 'com.example.studentTalentProfilingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEKSg01gWA8Z4Kv0NPCUfH_DCu4D1jO6Q',
    appId: '1:611009879331:web:7e471253d44bfbd2328096',
    messagingSenderId: '611009879331',
    projectId: 'student-talent-profiling-eaede',
    authDomain: 'student-talent-profiling-eaede.firebaseapp.com',
    storageBucket: 'student-talent-profiling-eaede.firebasestorage.app',
  );
}
