name: Deploy Web Dashboard to Vercel

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'web_dashboard/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'web_dashboard/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.ORG_ID }}
        vercel-project-id: ${{ secrets.PROJECT_ID }}
        working-directory: ./web_dashboard
